<Type Name="AsynchronousOperationException" FullName="System.IdentityModel.Services.AsynchronousOperationException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="a60b0ac8738325ff5ed2e18da4d2c5d6b40e2f36" /><Meta Name="ms.sourcegitcommit" Value="88014e1c5440e3df4f66ef04393854d15b1fd534" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="ru-RU" /><Meta Name="ms.lasthandoff" Value="09/05/2019" /><Meta Name="ms.locfileid" Value="70552145" /></Metadata><TypeSignature Language="C#" Value="public class AsynchronousOperationException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AsynchronousOperationException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.IdentityModel.Services.AsynchronousOperationException" />
  <TypeSignature Language="VB.NET" Value="Public Class AsynchronousOperationException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class AsynchronousOperationException : Exception" />
  <TypeSignature Language="F#" Value="type AsynchronousOperationException = class&#xA;    inherit Exception" />
  <AssemblyInfo>
    <AssemblyName>System.IdentityModel.Services</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary><span data-ttu-id="19bfd-101">Исключение, которое возникает в случае ошибки при выполнении асинхронной операции.</span><span class="sxs-lookup"><span data-stu-id="19bfd-101">The exception that is thrown when an error occurs during an asynchronous operation.</span></span></summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary><span data-ttu-id="19bfd-102">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" />.</span><span class="sxs-lookup"><span data-stu-id="19bfd-102">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class.</span></span></summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.Services.AsynchronousOperationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary><span data-ttu-id="19bfd-103">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" />.</span><span class="sxs-lookup"><span data-stu-id="19bfd-103">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="19bfd-104">Этот конструктор инициализирует свойство <xref:System.Exception.Message*> нового экземпляра, используя системное сообщение, описывающее ошибку.</span><span class="sxs-lookup"><span data-stu-id="19bfd-104">This constructor initializes the <xref:System.Exception.Message*> property of the new instance to a system-supplied message that describes the error.</span></span> <span data-ttu-id="19bfd-105">Это сообщение учитывает текущую культуру системы.</span><span class="sxs-lookup"><span data-stu-id="19bfd-105">This message takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="19bfd-106">В следующей таблице показаны начальные значения свойств для нового экземпляра.</span><span class="sxs-lookup"><span data-stu-id="19bfd-106">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="19bfd-107">Свойство.</span><span class="sxs-lookup"><span data-stu-id="19bfd-107">Property</span></span>|<span data-ttu-id="19bfd-108">Значение</span><span class="sxs-lookup"><span data-stu-id="19bfd-108">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException>|<span data-ttu-id="19bfd-109">`null`.</span><span class="sxs-lookup"><span data-stu-id="19bfd-109">`null`.</span></span>|  
|<xref:System.Exception.Message>|<span data-ttu-id="19bfd-110">Строка локализованного сообщения об ошибке.</span><span class="sxs-lookup"><span data-stu-id="19bfd-110">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.Services.AsynchronousOperationException : Exception -&gt; System.IdentityModel.Services.AsynchronousOperationException" Usage="new System.IdentityModel.Services.AsynchronousOperationException innerException" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException"><span data-ttu-id="19bfd-111">Исключение <see cref="T:System.Exception" />, являющееся причиной текущего исключения.</span><span class="sxs-lookup"><span data-stu-id="19bfd-111">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span></span> <span data-ttu-id="19bfd-112">Если значение параметра <paramref name="innerException" /> не равно <see langword="null" />, текущее исключение сгенерировано в блоке <see langword="catch" />, обрабатывающем внутреннее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-112">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="19bfd-113">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> с системным сообщением об ошибке и ссылкой на внутреннее исключение, которое стало причиной данного исключения.</span><span class="sxs-lookup"><span data-stu-id="19bfd-113">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class with a system-supplied error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="19bfd-114">Исключение, созданное как прямой результат предыдущего исключения, должно содержать в свойстве <xref:System.Exception.InnerException> ссылку на предыдущее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-114">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException> property.</span></span> <span data-ttu-id="19bfd-115"><xref:System.Exception.InnerException> Свойство возвращает то же значение, которое передается в конструктор.</span><span class="sxs-lookup"><span data-stu-id="19bfd-115">The <xref:System.Exception.InnerException> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="19bfd-116">В следующей таблице показаны начальные значения свойств для нового экземпляра.</span><span class="sxs-lookup"><span data-stu-id="19bfd-116">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="19bfd-117">Свойство.</span><span class="sxs-lookup"><span data-stu-id="19bfd-117">Property</span></span>|<span data-ttu-id="19bfd-118">Значение</span><span class="sxs-lookup"><span data-stu-id="19bfd-118">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException>|<span data-ttu-id="19bfd-119">Ссылка на внутреннее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-119">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message>|<span data-ttu-id="19bfd-120">Предоставляемое системой сообщение, описывающее ошибку.</span><span class="sxs-lookup"><span data-stu-id="19bfd-120">A system-supplied message that describes the error.</span></span> <span data-ttu-id="19bfd-121">Это сообщение учитывает текущую культуру системы.</span><span class="sxs-lookup"><span data-stu-id="19bfd-121">This message takes into account the current system culture.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.Services.AsynchronousOperationException : string -&gt; System.IdentityModel.Services.AsynchronousOperationException" Usage="new System.IdentityModel.Services.AsynchronousOperationException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="19bfd-122">Сообщение об ошибке, указывающее причину создания исключения.</span><span class="sxs-lookup"><span data-stu-id="19bfd-122">The error message that explains the reason for the exception.</span></span></param>
        <summary><span data-ttu-id="19bfd-123">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> с указанным сообщением об ошибке.</span><span class="sxs-lookup"><span data-stu-id="19bfd-123">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class with a specified error message.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="19bfd-124">Этот конструктор инициализирует <xref:System.Exception.Message> свойство нового исключения `message` с помощью параметра.</span><span class="sxs-lookup"><span data-stu-id="19bfd-124">This constructor initializes the <xref:System.Exception.Message> property of the new exception using the `message` parameter.</span></span> <span data-ttu-id="19bfd-125">Содержимое параметра `message` должно быть понятным пользователю.</span><span class="sxs-lookup"><span data-stu-id="19bfd-125">The content of `message` is intended to be understood by humans.</span></span> <span data-ttu-id="19bfd-126">Код, вызывающий этот конструктор, должен обеспечить локализацию данной строки в соответствии с текущим языком и региональными параметрами системы.</span><span class="sxs-lookup"><span data-stu-id="19bfd-126">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span></span>  
  
 <span data-ttu-id="19bfd-127">В следующей таблице показаны начальные значения свойств для нового экземпляра.</span><span class="sxs-lookup"><span data-stu-id="19bfd-127">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="19bfd-128">Свойство.</span><span class="sxs-lookup"><span data-stu-id="19bfd-128">Property</span></span>|<span data-ttu-id="19bfd-129">Значение</span><span class="sxs-lookup"><span data-stu-id="19bfd-129">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException>|<span data-ttu-id="19bfd-130">`null`.</span><span class="sxs-lookup"><span data-stu-id="19bfd-130">`null`.</span></span>|  
|<xref:System.Exception.Message>|<span data-ttu-id="19bfd-131">Строка сообщения об ошибке.</span><span class="sxs-lookup"><span data-stu-id="19bfd-131">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; AsynchronousOperationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.Services.AsynchronousOperationException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.IdentityModel.Services.AsynchronousOperationException" Usage="new System.IdentityModel.Services.AsynchronousOperationException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info"><span data-ttu-id="19bfd-132">Объект <see cref="T:System.Runtime.Serialization.SerializationInfo" />, содержащий данные сериализованных объектов.</span><span class="sxs-lookup"><span data-stu-id="19bfd-132">A <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object that holds the serialized object data.</span></span></param>
        <param name="context"><span data-ttu-id="19bfd-133">Объект <see cref="T:System.Runtime.Serialization.StreamingContext" />, содержащий контекстные сведения об источнике или назначении.</span><span class="sxs-lookup"><span data-stu-id="19bfd-133">A <see cref="T:System.Runtime.Serialization.StreamingContext" /> object that contains the contextual information about the source or destination.</span></span></param>
        <summary><span data-ttu-id="19bfd-134">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> с сериализованными данными.</span><span class="sxs-lookup"><span data-stu-id="19bfd-134">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class with serialized data.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="19bfd-135">Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке.</span><span class="sxs-lookup"><span data-stu-id="19bfd-135">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.Services.AsynchronousOperationException : string * Exception -&gt; System.IdentityModel.Services.AsynchronousOperationException" Usage="new System.IdentityModel.Services.AsynchronousOperationException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel.Services</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message"><span data-ttu-id="19bfd-136">Сообщение об ошибке, указывающее причину создания исключения.</span><span class="sxs-lookup"><span data-stu-id="19bfd-136">The error message that explains the reason for the exception.</span></span></param>
        <param name="innerException"><span data-ttu-id="19bfd-137">Исключение <see cref="T:System.Exception" />, являющееся причиной текущего исключения.</span><span class="sxs-lookup"><span data-stu-id="19bfd-137">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span></span> <span data-ttu-id="19bfd-138">Если значение параметра <paramref name="innerException" /> не равно <see langword="null" />, текущее исключение сгенерировано в блоке <see langword="catch" />, обрабатывающем внутреннее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-138">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span></span></param>
        <summary><span data-ttu-id="19bfd-139">Инициализирует новый экземпляр класса <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-139">Initializes a new instance of the <see cref="T:System.IdentityModel.Services.AsynchronousOperationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="19bfd-140">Исключение, созданное как прямой результат предыдущего исключения, должно содержать в свойстве <xref:System.Exception.InnerException> ссылку на предыдущее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-140">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException> property.</span></span> <span data-ttu-id="19bfd-141"><xref:System.Exception.InnerException> Свойство возвращает то же значение, которое передается в конструктор.</span><span class="sxs-lookup"><span data-stu-id="19bfd-141">The <xref:System.Exception.InnerException> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="19bfd-142">В следующей таблице показаны начальные значения свойств для нового экземпляра.</span><span class="sxs-lookup"><span data-stu-id="19bfd-142">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="19bfd-143">Свойство.</span><span class="sxs-lookup"><span data-stu-id="19bfd-143">Property</span></span>|<span data-ttu-id="19bfd-144">Значение</span><span class="sxs-lookup"><span data-stu-id="19bfd-144">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException>|<span data-ttu-id="19bfd-145">Ссылка на внутреннее исключение.</span><span class="sxs-lookup"><span data-stu-id="19bfd-145">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message>|<span data-ttu-id="19bfd-146">Строка сообщения об ошибке.</span><span class="sxs-lookup"><span data-stu-id="19bfd-146">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>
