<Type Name="EventDeliveryFailedException" FullName="System.Workflow.Activities.EventDeliveryFailedException">
  <Metadata><Meta Name="ms.openlocfilehash" Value="58706e006701f6f1a1bc516ebb4d607e3dfaac3b" /><Meta Name="ms.sourcegitcommit" Value="88014e1c5440e3df4f66ef04393854d15b1fd534" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="ru-RU" /><Meta Name="ms.lasthandoff" Value="09/05/2019" /><Meta Name="ms.locfileid" Value="70578785" /></Metadata><TypeSignature Language="C#" Value="public sealed class EventDeliveryFailedException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit EventDeliveryFailedException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.Workflow.Activities.EventDeliveryFailedException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class EventDeliveryFailedException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class EventDeliveryFailedException sealed : SystemException" />
  <TypeSignature Language="F#" Value="type EventDeliveryFailedException = class&#xA;    inherit SystemException" />
  <AssemblyInfo>
    <AssemblyName>System.Workflow.Activities</AssemblyName>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8">
      <AttributeName>System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>Исключение, которое создается при невозможности доставки возникшего на узле события экземпляру рабочего процесса. Как правило, событие возникает из класса <see cref="T:System.Workflow.Activities.ExternalDataExchangeService" /> экземпляра рабочего процесса. Этот класс не наследуется.</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
  
> [!NOTE]
>  [!INCLUDE[DeprecatedContent](~/includes/deprecatedcontent-md.md)]  
  
 Следующая строка добавляется в журнал событий при возникновении этого исключения: событие "{1}" в интерфейсе типа "{0}" для идентификатора{2}экземпляра "" не может быть доставлено.  
  
 При использовании рабочего потока конечного автомата можно получить исключение с сообщением: "Очередь "{0}"' не включена". Это происходит, когда при текущем состоянии конечного автомата не известно, как обработать определенное событие. Например, если какое-либо состояние, отличное от текущего, содержит действие <xref:System.Workflow.Activities.EventDrivenActivity>, содержащее действие <xref:System.Workflow.Activities.HandleExternalEventActivity>, которое представляется очередью "{0}".  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>Инициализирует новый экземпляр класса <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" />.</summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>3.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>Инициализирует новый экземпляр класса <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" />.</summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.Workflow.Activities.EventDeliveryFailedException : string -&gt; System.Workflow.Activities.EventDeliveryFailedException" Usage="new System.Workflow.Activities.EventDeliveryFailedException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>3.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">Сообщение об ошибке с объяснением причины исключения.</param>
        <summary>Инициализирует новый экземпляр класса <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" />, используя сообщение об ошибке, в котором объясняется причина исключения.</summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public EventDeliveryFailedException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Workflow.Activities.EventDeliveryFailedException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; EventDeliveryFailedException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.Workflow.Activities.EventDeliveryFailedException : string * Exception -&gt; System.Workflow.Activities.EventDeliveryFailedException" Usage="new System.Workflow.Activities.EventDeliveryFailedException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Workflow.Activities</AssemblyName>
        <AssemblyVersion>3.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">Сообщение об ошибке с объяснением причины исключения.</param>
        <param name="innerException">Объект <see cref="T:System.Exception" />, вызвавший это исключение.</param>
        <summary>Инициализирует новый экземпляр класса <see cref="T:System.Workflow.Activities.EventDeliveryFailedException" />, используя сообщение об ошибке, в котором объясняется причина исключения, и объект <see cref="T:System.Exception" />, вызвавший это исключение.</summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>
